name: Release 

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./scala3
    name: Release on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v5
      with:
      # restore and save a cache using this key
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command sbt nativeImage
      name: Build native Image
    - run: upx ./target/native-image/cli-graal
      name: Compress binary with UPX
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./scala3/target/native-image/cli-graal
        body: |
          Release Notes
        draft: true
        prerelease: true

